- backend/program/content/plex_watchlist.py
This fixes the item matching to current library. Works.
Also changed to logging items that are added to info, rest to debug.
> Fix update filter. Switch to debug logging.

- Dockerfile
- README.md
- backend/program/media.py
- backend/program/updaters/trakt.py
- frontend/src/routes/status/+page.svelte
Fix trakt_data issue not finding the relative path. Switched to use absolute path instead.
> Fix media items

- frontend/package.json
- frontend/pnpm-lock.yaml
- frontend/src/lib/components/status-media-card.svelte
- frontend/src/lib/helpers.ts
- frontend/src/lib/types.ts
- frontend/src/routes/+page.server.ts
- frontend/src/routes/+page.svelte
- frontend/src/routes/status/+page.server.ts
- frontend/src/routes/status/+page.svelte
- frontend/svelte.config.js
- Switched api endpoints of python in frontend to `127.0.0.1`
- Moved to sveltekit2 (delete your node_modules and lock file!)
- Some minor ui improvements
> feat: frontend improvements

- README.md
- backend/program/__init__.py
- backend/program/libraries/plex.py
- backend/program/symlink.py
- backend/utils/default_settings.json
NOTE! This will break with old settings so please convert settings.json after merge!
> Move mount settings to general settings, fix section updating

- backend/program/updaters/trakt.py
- Fixes a breaking change in Trakt.py
> tidy imports

- .github/workflows/docker-build.yml
* add arm64 build
* add pushing built image to ghcr.io
* update GHA sections to newest versions
Added armv7 but it breaks on esbuild install, so removed for now. need to look into it further.
> Update github actions with multiarch etc

- .github/workflows/docker-build.yml
> add explicit permissions to GHA

- backend/program/plex.py
> GH-112 - Look for only movies and shows

- backend/program/media/item.py
- backend/program/media/state.py
- backend/program/realdebrid.py
- backend/program/symlink.py
> Simplified downloading logic and modified state matchine

- backend/utils/parser.py
Ready to be tested.
Switched to handling the unwanted quality manually.
> fix: handle bad quality manually in parser

- backend/program/content/overseerr.py
> fix: correct parsing of external id's

- backend/program/realdebrid.py
- Made wanted formats return only wanted formats.
> Rd_rewrite

- backend/program/plex.py
- backend/program/symlink.py
Small refactor to minimize indentation and improve readability.
> Plex refactor

- backend/program/program.py
- backend/program/realdebrid.py
- frontend/src/hooks.server.ts
- frontend/src/lib/components/command-item.svelte
- frontend/src/lib/components/header.svelte
- frontend/src/lib/stores.ts
- frontend/src/routes/+layout.svelte
- frontend/src/routes/+page.svelte
- frontend/src/routes/onboarding/+page.svelte
- frontend/src/routes/settings/about/+page.server.ts
- frontend/src/routes/settings/about/+page.svelte
- frontend/src/routes/settings/content/+page.server.ts
- frontend/src/routes/settings/general/+page.server.ts
- frontend/src/routes/settings/mediaserver/+page.server.ts
- frontend/src/routes/settings/scrapers/+page.server.ts
Decided to fix up the frontend onboarding, which also fixes some bugs on the backend regarding services. Things should be pretty good now.
- Fixes onboarding due to previous service statuses.
- Fixes fetching latest Iceburg version infinitely loading.
- Makes command palette a clickable button.
- About page now has contributors and sponsors.
> Fixes Frontend and adds some cool things on the frontend.

- backend/controllers/webhooks.py
- backend/program/cache.py
- backend/program/content/trakt.py
- backend/program/downloaders/realdebrid.py
- backend/program/libraries/plex.py
- backend/program/media/container.py
- backend/program/media/item.py
- backend/program/program.py
- backend/program/scrapers/torbox.py
- backend/program/settings/models.py
- backend/program/symlink.py
- backend/utils/request.py
- Trakt Support
- Symlink blacklisting infohash based on failure to symlink after 3 tries
- Other small minor tweaks..
> feat: finish up trakt integration

- backend/program/settings/manager.py
> Use default settings when the provided settings file can't be parsed

- backend/program/content/plex_watchlist.py
> Fix plex qatchlist return type when not using rss

- backend/program/scrapers/jackett.py
> Jackett improvements

- backend/program/scrapers/__init__.py
- backend/program/scrapers/mediafusion.py
- backend/program/settings/models.py
- backend/program/types.py
- frontend/src/lib/forms/helpers.ts
- frontend/src/lib/forms/scrapers-form.svelte
- frontend/src/routes/+page.svelte
> Add mediafusion scraper

- frontend/src/hooks.server.ts
> fix: minor fix to hooks.server.ts

- backend/controllers/default.py
- backend/controllers/items.py
- backend/controllers/settings.py
- frontend/src/lib/forms/content-form.svelte
- frontend/src/lib/forms/helpers.ts
> API Changes

- Dockerfile
- backend/program/content/overseerr.py
- backend/program/scrapers/orionoid.py
- docker-compose-dev.yml
- docker-compose.yml
- poetry.lock
- pyproject.toml
> docker: small fixes

- backend/program/content/mdblist.py
- backend/program/content/overseerr.py
- backend/program/settings/models.py
> fix: change mdblist str to int

- backend/program/libraries/symlink.py
- backend/program/program.py
- backend/program/settings/models.py
- backend/program/symlink.py
- backend/program/updaters/plex.py
> Force refresh

- backend/program/symlink.py
> fix: episode attr error when checking Show type

- backend/program/libraries/symlink.py
> fix: convert str to path first

- backend/program/updaters/plex.py
> fix: change Path objs to str

- README.md
Signed-off-by: David Young <davidy@funkypenguin.co.nz>
> Propose update to README

- .github/workflows/frontend-battery.yml
> Run frontend linting only when frontend has changes

- backend/main.py
> chore: minor fastapi tweaks

- backend/main.py
- backend/program/downloaders/realdebrid.py
> fix: RTN import incorrect after updating package

- backend/program/scrapers/__init__.py
- backend/program/scrapers/prowlarr.py
- backend/program/settings/models.py
> Feat-prowlarr

- backend/controllers/default.py
- backend/program/downloaders/realdebrid.py
- backend/program/settings/models.py
> Add Proxy Support to Real Debrid

- .github/ISSUE_TEMPLAYE/config.yml
- backend/__init__.py
- backend/main.py
- backend/program/libraries/symlink.py
- backend/program/settings/models.py
- backend/program/symlink.py
- backend/utils/logger.py
- backend/utils/request.py
> Small Tweaks

- frontend/static/fonts/Satoshi-Black.woff2:Zone.Identifier
- frontend/static/fonts/Satoshi-Black.woff:Zone.Identifier
- frontend/static/fonts/Satoshi-Bold.woff2:Zone.Identifier
- frontend/static/fonts/Satoshi-Bold.woff:Zone.Identifier
- frontend/static/fonts/Satoshi-Light.woff2:Zone.Identifier
- frontend/static/fonts/Satoshi-Light.woff:Zone.Identifier
- frontend/static/fonts/Satoshi-Medium.woff2:Zone.Identifier
- frontend/static/fonts/Satoshi-Medium.woff:Zone.Identifier
- frontend/static/fonts/Satoshi-Regular.woff2:Zone.Identifier
- frontend/static/fonts/Satoshi-Regular.woff:Zone.Identifier
> chore: remove unnecessary font identifier

- backend/program/indexers/trakt.py
> Patch changes trakt

- backend/program/program.py
- backend/program/scrapers/__init__.py
> Partial state handling

- backend/program/scrapers/jackett.py
- backend/program/scrapers/prowlarr.py
> Fix: jacket-prowlarr params based on what indexer reports

- backend/program/content/trakt.py
> Fix Collections

- backend/program/scrapers/__init__.py
> Fix: Remove timeout for slow scrapers, prevents race condition

- backend/program/content/trakt.py
second try's the charm, i hope
> Fixed Collections Again

- backend/program/scrapers/zilean.py
change .title to get_top_title(), and include the Show type in the pattern matching.
> Update to include get_top_title() as well as Show

- frontend/src/lib/components/header.svelte
- frontend/src/lib/components/media-item.svelte
- frontend/src/routes/+page.svelte
> fix: summary page incomplete items taking over header

- frontend/src/lib/components/header.svelte
- frontend/src/routes/+page.svelte
> fix: text color on light theme

- backend/program/db/db_functions.py
- backend/program/program.py
> Various fixes

- backend/program/db/db_functions.py
> Release 080 patches

- Dockerfile
> fix: add BACKEND_URL arg to avoid build error

- Dockerfile
- frontend/src/lib/forms/helpers.server.ts
- frontend/src/lib/forms/helpers.ts
- frontend/src/routes/settings/content/+page.server.ts
- frontend/src/routes/settings/general/+page.server.ts
- frontend/src/routes/settings/mediaserver/+page.server.ts
- frontend/src/routes/settings/scrapers/+page.server.ts
> refactor: move code with private env to different file

- Dockerfile
- frontend/src/hooks.server.ts
- frontend/src/lib/forms/helpers.server.ts
- frontend/src/routes/+page.server.ts
- frontend/src/routes/library/+page.server.ts
- frontend/src/routes/onboarding/1/+page.server.ts
- frontend/src/routes/onboarding/2/+page.server.ts
- frontend/src/routes/onboarding/3/+page.server.ts
- frontend/src/routes/onboarding/4/+page.server.ts
- frontend/src/routes/settings/about/+page.server.ts
- frontend/src/routes/settings/content/+page.server.ts
- frontend/src/routes/settings/mediaserver/+page.server.ts
- frontend/src/routes/settings/scrapers/+page.server.ts
- frontend/src/routes/summary/+page.server.ts
> fix: switch to dynamic private env

- backend/program/settings/manager.py
- backend/program/settings/migratable.py
- backend/program/settings/models.py
- backend/tests/test_settings_migration.py
- poetry.lock
- pyproject.toml
Migrate settings from older versions to new version on run.
Saves settings after model assignment
> Settings migration

- backend/program/content/plex_watchlist.py
> Fix yield of plex watchlist

- Dockerfile
- entrypoint.sh
> Remove frontend from docker

- src/controllers/actions.py
- src/main.py
> feat: Add endpoint to manually request items

- README.md
- docker-compose-postgres-host.yml
Created docker-compose.yml file with postgress and network_mode: host.
> Created multiple docker files and updated readme to latest version

- src/program/program.py
instead of exiting on a failure for enhancing metadata, just skip it.
> fix: continue instead of exit on failed to enhance metadata

- src/program/program.py
> fix: crash on failed metadata enhancement

- src/program/downloaders/realdebrid.py
- src/program/program.py
- src/program/updaters/__init__.py
> fix: validate rd user data and updater settings on startup

- .github/workflows/docker-build.yml
- Dockerfile
> fix: docker metadata from release please

- .github/workflows/docker-build.yml
> Fix ruff errors

- src/main.py
> fix: api port back to 8080

- src/controllers/default.py
- src/program/db/db_functions.py
- src/program/program.py
- src/program/symlink.py
> Symlink Handling & Fixes

- docker-compose-full.yml
- docker-compose.yml
Adds the required database config for riven-frontend
> add database to frontend docker compose

- src/controllers/items.py
- src/program/db/db_functions.py
- src/program/downloaders/realdebrid.py
- src/program/indexers/trakt.py
- src/program/libraries/symlink.py
- src/program/media/item.py
- src/program/media/stream.py
- src/program/media/subtitle.py
- src/program/post_processing/__init__.py
- src/program/post_processing/subliminal.py
- src/program/program.py
- src/program/settings/models.py
- src/program/state_transition.py
- src/program/symlink.py
> feat: add a subtitle provider (subliminal)

- CHANGELOG.md
- CODE_OF_CONDUCT.md
- CONTRIBUTING.md
- LICENSE.md
- README.md
- poetry.lock
- pyproject.toml
- src/program/db/db.py
- src/program/program.py
- src/program/scrapers/zilean.py
Fixed by closing SQLAlchemy sessions in item retry loop, and expunging items (which are reloaded again anywhere by the item services.
Added connection pool options to increase performance now we are in postgres. Postgres by default sets connection pool to 100, so lets use half of em.
Should eventually become a config option!
Close SQLAlchemy sessions after use to prevent memory leaks.
Add connection pool options to SQLAlchemy engine to improve performance.
Add memray dependency for memory profiling, can be used under poetry shell.
> fix: address memory leak

- poetry.lock
- pyproject.toml
- src/program/db/db.py
- src/program/program.py
This reverts commit 464b38c79b008343c08aed1556a273abb10c2297.
> Revert "fix: address memory leak by closing SQLAlchemy sessions and add connection pool options"

- src/program/db/db.py
- src/program/db/db_functions.py
- src/program/media/item.py
- src/program/media/stream.py
- src/program/media/subtitle.py
- src/program/post_processing/subliminal.py
- src/program/program.py
- src/utils/event_manager.py
> Revert "feat: add indexing and maintenance functions to database operations"

- src/program/db/db.py
- src/program/db/db_functions.py
- src/program/media/item.py
- src/program/media/stream.py
- src/program/media/subtitle.py
- src/program/post_processing/subliminal.py
- src/program/program.py
- src/utils/event_manager.py
> Revert "Revert "feat: add indexing and maintenance functions to database operations""

- src/controllers/items.py
- src/program/content/overseerr.py
- src/program/db/db_functions.py
- src/program/downloaders/realdebrid.py
- src/program/indexers/trakt.py
- src/program/media/item.py
- src/program/program.py
- src/program/symlink.py
- Added detailed logging for various scenarios in `realdebrid.py` to improve debugging.
- Enhanced error handling in `_download_item` method in `realdebrid.py`.
- Introduced session refresh for blacklisted streams in `realdebrid.py` and `item.py`.
- Added `requested_id` attribute to `MediaItem` class in `item.py`.
- Updated `copy_attributes` method in `trakt.py` to include new attributes.
- Refactored `delete_item_symlinks` method in `symlink.py` for better readability.
- Improved session management in `db_functions.py` by adding `store_state` calls.
- Enhanced `Overseerr` class in `overseerr.py` to include `requested_id` and improved logging.
- Minor code cleanups and added type hints for better code quality.
feat: Removal of Symlinks and Overseerr requests on removal of item from riven.
> refactor: Refactor codebase to improve logging, error handling, and session management

- src/program/downloaders/__init__.py
- src/program/downloaders/alldebrid.py
- src/program/downloaders/realdebrid.py
- src/program/downloaders/shared.py
- src/tests/test_alldebrid_downloader.py
- src/tests/test_data/alldebrid_magnet_delete.json
- src/tests/test_data/alldebrid_magnet_instant.json
- src/tests/test_data/alldebrid_magnet_instant_unavailable.json
- src/tests/test_data/alldebrid_magnet_status_one_downloading.json
- src/tests/test_data/alldebrid_magnet_status_one_ready.json
- src/tests/test_data/alldebrid_magnet_upload_not_ready.json
- src/tests/test_data/alldebrid_magnet_upload_ready.json
Resolves: alldebrid not working
The recent realdebrid downloader refactor broke alldebrid. This change updates alldebrid to match the new downloader patterns.
> fix: refactor and re-enable alldebrid

- src/controllers/items.py
> fix: reset the scraped time when replacing magnets

- src/program/media/item.py
- src/program/media/subtitle.py
> fix: serialize subtitles for api response

- README.md
> docs: remove duplicate service from readme

- src/program/downloaders/__init__.py
- src/program/scrapers/prowlarr.py
> fix: service endpoint response for downloaders

- src/program/libraries/symlink.py
- src/program/program.py
> fix: fixed scanning of incorrect dirs and files when rebuilding symlinks

- src/program/symlink.py
> fix: files sometimes not found in mount

- src/utils/sse_manager.py
> chore: send sse data in different format

- src/program/db/db_functions.py
- src/routers/secure/items.py
> fix: retry api now resets scraped_at

- src/program/downloaders/__init__.py
- src/program/downloaders/torbox.py
- src/program/indexers/trakt.py
- src/routers/secure/items.py
- src/utils/torrent.py
> feat: add manual torrent adding

- src/program/downloaders/realdebrid.py
- src/program/downloaders/shared.py
- src/program/settings/models.py
> feat: filesize filter

- src/routers/secure/items.py
> fix: misleading message when manually adding a torrent

- .github/workflows/docker-build-dev.yml
- src/program/db/db.py
- src/program/db/db_functions.py
- src/program/downloaders/__init__.py
- src/program/downloaders/alldebrid.py
- src/program/downloaders/realdebrid.py
- src/program/downloaders/shared.py
- src/program/media/item.py
- src/program/media/stream.py
- src/program/post_processing/__init__.py
- src/routers/secure/items.py
- src/routers/secure/scrape.py
- src/utils/event_manager.py
chore: option to manually trigger dev build
refactor: rework /scrape to enable manual scraping via ui
feat: stream management endpoints
chore: refactore alldebrid, untested
> refactor: simplify downloaders

- src/program/db/db_functions.py
- src/routers/secure/scrape.py
> fix: duplicate item after scraping for media that isn't in the database already

- src/program/services/indexers/trakt.py
- src/routers/secure/default.py
Also add episode and season types to composites.
> fix: correct type hint for incomplete_retries in StatsResponse

- src/routers/secure/items.py
- Ensure cancellation and deletion of episodes and seasons for shows
- Add handling for nested media items in the remove_item function
> fix: handle removal of nested media items in remove_item function

- src/program/db/db_functions.py
- src/program/managers/event_manager.py
- src/program/state_transition.py
- src/routers/secure/scrape.py
- Added asyncio support for asynchronous operations in scraping sessions.
- Improved session management with additional checks for item existence.
- Enhanced event manager to handle cancelled futures and improve logging.
- Updated state transition logic to handle NoneType for existing items.
- Introduced joinedload to always ensure we get a mediaitem and its parent id.
> feat: enhance session management and event processing

- src/program/services/downloaders/realdebrid.py
> fix: invalid rd instant availibility call if no infohashes should be checked
