- .dockerignore
- .github/workflows/docker-build.yml
- Dockerfile
- README.md
- backend/main.py
- backend/program/program.py
- backend/program/updaters/trakt.py
- backend/utils/settings.py
- requirements.txt
Should fix trakt_data.pkl path.
Also adds Docker support + GH Action for pushing image to Docker Hub
`spoked/iceberg:latest`
> Add docker. Other light fixes for paths

- Dockerfile
- README.md
- entrypoint.sh
Allow users to set PUID/PGID in compose. If this doesn't get set, Plex won't see the Symlink files as Plex typically isn't ran as the root users. Make sure to set the PUID and PGID in your compose to the same as what Plex uses.
> fix symlink permission issue

- Dockerfile
- entrypoint.sh
- If the Provided PGID Already Exists: The script checks if a group with the provided PGID already exists in the container. If it does, the script will use this existing group instead of creating a new one. It prints out the name of the existing group for clarity.
- If the Provided PUID Already Exists: Similarly, if a user with the provided PUID already exists, the script will use this existing user. It prints out the username of the existing user.
> Fix dockerfile

- backend/program/scrapers/torrentio.py
- Fixes the random 500: handler error's.
This was due to the url being incorrect in the torrentio links when scraping.
> set scrape type to series instad of show. invalid url before.

- backend/program/content/__init__.py
- backend/program/content/listrr.py
- backend/program/scrapers/torrentio.py
- backend/program/updaters/trakt.py
- backend/utils/default_settings.json
Tested, ready for review.
New settings:
```json
"listrr": {
"enabled": false,
"movie_lists": [""],
"show_lists": [""],
"api_key": "",
"update_interval": 80
},
```
> feat: Listrr Support Added

- .github/workflows/docker-build-dev.yml
closes https://github.com/dreulavelle/iceberg/issues/152
simple secondary build for dev branch on push only.
> add dev branch builds with :dev tag

- .github/workflows/docker-build.yml
this will take the git commit hash and add it as docker image tag but will limit it to 5 characters.
> add commit hash based docker image tags

- backend/program/__init__.py
- backend/program/realdebrid.py
- backend/program/scrapers/jackett.py
- backend/program/scrapers/orionoid.py
- backend/program/scrapers/torrentio.py
- backend/program/symlink.py
- frontend/src/lib/forms/helpers.ts
- frontend/src/routes/settings/about/+page.svelte
- frontend/src/routes/settings/content/+page.server.ts
- frontend/src/routes/settings/general/+page.server.ts
- frontend/src/routes/settings/mediaserver/+page.server.ts
- frontend/src/routes/settings/scrapers/+page.server.ts
* rework in progress.
* fix: correct limits for orionoid
* fix: switch to comprehensions
* fix: disable plex logging for id mismatches
* time for sleep. rework still wip.
* feat: parser works. needs more work. language needs a rewrite. disabled for now.
* fix: overseerr bug on using external ids
* fix: remove plex debug line for users
* disable tvdb checks from listrr, overseerr, plex. needs reworked.
* set torrentio to disabled by default. removed parse logs. raised torrentio limit slightly.
* Set all default settings to disabled by default for onboarding
* add extra logging attr. for debugging large groups of data.
* feat: started status page rewrite
* add dev branch builds with :dev tag (#165)
* fix: listrr validation
* rework in progress.
* fix: correct limits for orionoid
* fix: …
> fix dev history

- backend/program/libaries/plex.py
- backend/program/libaries/symlink.py
- backend/program/program.py
- backend/program/settings/models.py
SymlinkLibrary needed a validation step, and also needs to be moved to start after Symlinker to make sure the correct paths are created.  Additionally we should be waiting for all services to validate like we used to.
> Alternate startup logic to correctly wait on services to validate

- backend/program/content/mdblist.py
- backend/program/settings/models.py
This PR allows the ability of defining list with the url. Making it easy to copy and paste any list on mdblist into river.
List ids are also still allowed and logic is kept as is
```
mdblist": {
"update_interval": 300,
"enabled": true,
"api_key": "",
"lists": [
"https://mdblist.com/lists/hdlists/latest-hd-crime-movies-top-rated-from-1980-to-today",
2567
]
}
```
> feat: add support for mdblist urls

- backend/program/settings/models.py
Seems it got lost during a merge
> Return of the string type for mdb lists

- backend/program/content/trakt.py
Riven is only fetching the first 10 items of any Trakt collections/lists/watchlist:
```
24-06-18 15:49:02 | 🎵 TRAKT     | trakt.run - New items fetched from Watchlist: 10
24-06-18 15:49:02 | 🎵 TRAKT     | trakt.run - New items fetched from User Lists: 10
24-06-18 15:49:02 | 🎵 TRAKT     | trakt.run - Total new items fetched: 20
```
Now it is fetching all of the items if params.limit is not set:
```
24-06-18 17:02:28 | 🎵 TRAKT     | trakt.run - New items fetched from Watchlist: 14
24-06-18 17:02:28 | 🎵 TRAKT     | trakt.run - New items fetched from User Lists: 25
24-06-18 17:02:28 | 🎵 TRAKT     | trakt.run - Total new items fetched: 39
```
> Bugfix - Fetch all pages unless limit is set

- backend/program/scrapers/__init__.py
- backend/program/scrapers/zilean.py
- backend/program/settings/models.py
- backend/program/types.py
Zilean is a service that allows you to search for DebridMediaManager sourced arr-less content. When the service is started, it will automatically download and index all the DMM shared hashlists and index them using Lucene. The service provides a search endpoint that allows you to search for content using a query string, and returns a list of filenames and infohashes. There is no clean filtering applied to the search results, the idea behind this endpoint is Riven performs that using RTN. The DMM import reruns on missing pages every hour. Its written exclusively for Riven
https://github.com/iPromKnight/zilean
> Add Zilean scraper: untested - Spoked can test :D

- Dockerfile
- entrypoint.sh
Fixes the issue where riven won't start if PUID and PGID are not set to 1000:1000
Dockerfile was adding the "riven" user with 1000:1000,  entrypoint.sh tried to add it again if PUID/PGID were set different.
Now entrypoint.sh is the only place that adds & chowns, with a special test for the root user (PUID 0)
> allow PUID/GUID other than 1000:1000

- frontend/src/lib/components/header.svelte
- frontend/src/lib/components/ui/aspect-ratio/aspect-ratio.svelte
- frontend/src/lib/components/ui/aspect-ratio/index.ts
- frontend/src/routes/+page.svelte
> feat: add top rated section

- backend/program/scrapers/__init__.py
- backend/program/scrapers/annatar.py
- backend/program/scrapers/comet.py
- backend/program/settings/models.py
> Comet Scraper

- backend/program/scrapers/zilean.py
The Zilean scraper has been refactored to support the MediaItem class. Previously, it only supported the Movie class. The 'aired_at' attribute of a Movie instance is now replaced with the 'year' attribute of a MediaItem instance. This change allows more flexibility in handling different types of media items beyond just movies.
> Refactor Zilean scraper for MediaItem support

- .github/workflows/release-please.yaml
Hey!
This PR adds support for versioned releases based on [conventional commit messages](https://www.conventionalcommits.org/en/v1.0.0/), using https://github.com/googleapis/release-please.
To use it to cut releases, just commit to main with `feat: <blah>` or `fix: <blah>`, and it'll open a PR to capture all your changes since the last release. When you're ready to release, just merge the PR.
You can make it start on a particular version number by including `"Release-As: 0.7.5"` in your commit **body** :)
You'll need a GH actions secret named `RELEASE_PLEASE_TOKEN`, containing a fine-grained token with the following permissions to this repo:
* Contents: Read/Write
* Metadata: Read (mandatory)
* Pull requests: Read/Write
Assuming this workflow is in place, ElfHosted can build off your …
> Add releaseplease workflow for versioned releases (supports ElfHosted)

- README.md
- docker-compose-dev.yml
- docker-compose.yml
- entrypoint.sh
- frontend/src/hooks.server.ts
- frontend/src/lib/components/header.svelte
- frontend/src/lib/forms/helpers.ts
- frontend/src/routes/+page.server.ts
- frontend/src/routes/+page.svelte
- frontend/src/routes/library/+page.server.ts
- frontend/src/routes/onboarding/1/+page.server.ts
- frontend/src/routes/onboarding/2/+page.server.ts
- frontend/src/routes/onboarding/3/+page.server.ts
- frontend/src/routes/onboarding/4/+page.server.ts
- frontend/src/routes/settings/about/+page.server.ts
- frontend/src/routes/settings/content/+page.server.ts
- frontend/src/routes/settings/general/+page.server.ts
- frontend/src/routes/settings/mediaserver/+page.server.ts
- frontend/src/routes/settings/scrapers/+page.server.ts
- frontend/src/routes/summary/+page.server.ts
> feat!: add BACKEND_URL environment variable to support for custom backend URL

- src/program/downloaders/torbox.py
> Torbox Support

- src/program/scrapers/comet.py
comet validation wasnt using the wrapped response attribute `is_ok` to check if the response received the 200 status
> fix: comet validation needed is_ok on response instead of ok

- .github/workflows/backend-battery.yml.disabled
- .github/workflows/conventional-commits.yml
- README.md
> feat: enforce conventional commits

- poetry.lock
- pyproject.toml
- src/program/db/db.py
- src/program/program.py
Fixed by closing SQLAlchemy sessions in item retry loop, and expunging items (which are reloaded again anywhere by the item services.
Added connection pool options to increase performance now we are in postgres. Postgres by default sets connection pool to 100, so lets use half of em.
Should eventually become a config option!
- Close SQLAlchemy sessions after use to prevent memory leaks.
- Add connection pool options to SQLAlchemy engine to improve performance.
- Add `memray` dependency for memory profiling, can be used under poetry shell.
> fix: address memory leak

- src/program/db/db.py
- src/program/db/db_functions.py
- src/program/media/item.py
- src/program/media/stream.py
- src/program/media/subtitle.py
- src/program/post_processing/subliminal.py
- src/program/program.py
- src/utils/event_manager.py
- Introduced `_get_item_ids` function to retrieve related item IDs for shows and seasons.
- Added `ensure_alembic_version_table` and `vacuum_and_analyze_index_maintenance` functions for database maintenance.
- Implemented new indexes for `StreamRelation`, `StreamBlacklistRelation`, `Stream`, `MediaItem`, and `Subtitle` tables to improve query performance.
- Updated `_run_thread_with_db_item` to handle item insertion and retrieval more efficiently.
- Modified event manager to use `_get_item_ids` for checking related items in the queue.
- Scheduled `vacuum_and_analyze_index_maintenance` to run daily.
- Enhanced `run_migrations` to handle alembic version table creation and error recovery.
- Added conditional check for enabling subliminal settings in post-processing.
> feat: add indexing and maintenance functions to database operations

- dev/attach-memray.sh
- src/program/db/db_functions.py
- src/program/downloaders/__init__.py
- src/program/downloaders/alldebrid.py
- src/program/downloaders/realdebrid.py
- Introduced `attach-memray.sh` script to attach memray to the running `main.py` process.
- Updated `realdebrid.py` to increase the number of rows per page to 10 and use `blacklist_stream` function.
- Removed redundant log message in `alldebrid.py`.
- Imported `States` in `downloaders/__init__.py`.
- Minor refactoring in `db_functions.py` for consistency.
> feat: Add memray attachment script and update stream handling in downloaders

- dev/attach-memray.sh
- src/program/db/db_functions.py
- src/program/downloaders/realdebrid.py
- src/program/media/item.py
- Updated `reset_streams` and `blacklist_stream` functions in `db_functions.py` to accept `MediaItem` object instead of `media_item_id`.
- Modified `realdebrid.py` and `item.py` to reflect changes in `blacklist_stream` function signature.
- Fixed `attach-memray.sh` script to attach memray to the first `main.py` process.
> refactor: Refactor `blacklist_stream` and `reset_streams` functions to use `MediaItem` object

- src/program/db/db_functions.py
- src/program/downloaders/realdebrid.py
- src/program/media/item.py
- Added session.merge(item) to ensure MediaItem is merged into the session before performing operations in `reset_streams` and `blacklist_stream`.
- Updated `stream_hashes` to store lowercase infohash keys in realdebrid.py.
- Removed unused imports in item.py.
> fix: Ensure MediaItem is merged into session before operations in db_functions.py

- src/program/db/db_functions.py
- src/program/media/item.py
- Corrected the `reset_streams` function call to pass the `MediaItem` object instead of its ID.
- Added a line to reset the `active_stream` attribute to `None` in the `reset_streams` function.
- Ensured the script exits after performing hard reset or symlink repair based on environment variables.
> fix: Fix `reset_streams` function call and ensure `active_stream` is reset

- src/utils/logger.py
- Added custom color and icon settings for default log levels: DEBUG, INFO, WARNING, CRITICAL, and SUCCESS.
- Ensured consistency in log level configuration by applying the same method for both custom and default log levels.
Blue was giving me a headache for debug in dozzle :D
> feat: Add custom color and icon settings for default log levels in logger setup

- poetry.lock
- pyproject.toml
- src/program/db/db_functions.py
- src/tests/test_container.py
- src/tests/test_db_functions.py
- Corrected the parameter type for the `stream` argument in the `blacklist_stream` function from `str` to `Stream`.
- Added exception handling and logging for errors in the `blacklist_stream` function.
- Ensured session commit and refresh are always executed in `blacklist_stream` when the session is closed.
- Added an exit statement at the end of the script to ensure proper termination.
- Introduced `package-mode` flag in `pyproject.toml`.
- Updated `pytest` dependency to version `8.3.2`.
- Added `testcontainers` dependency.
- Commented out all test cases in `test_container.py` as the container is no longer used. These need to be reworked.
- Added start of db function tests which utilise test-containers to spin up a container, shared across all tests. Between each test, the state of the …
> fix: incorrect parameter type in `blacklist_stream` function

- src/controllers/items.py
- src/program/db/db_functions.py
- src/program/media/item.py
- src/tests/test_db_functions.py
- Introduced `delete_media_item`, `delete_media_item_by_id`, `delete_media_item_by_item_id`, and `delete_media_items_by_ids` functions in `db_functions.py` to handle deletion of MediaItems and their associated relationships.
- Updated `MediaItem` relationships to include cascade delete options.
- Refactored `remove_item` endpoint in `items.py` to use the new deletion functions.
- Added tests for the new deletion functions in `test_db_functions.py`.
> feat: Add functions to delete MediaItems and associated relationships

- src/controllers/items.py
- src/program/db/db_functions.py
- src/tests/test_db_functions.py
- Introduced `get_media_items_by_ids` function in `db_functions.py` to retrieve multiple MediaItems by their IDs.
- Updated `remove_item` endpoint in `items.py` to use `get_media_items_by_ids` for validating and deleting media items.
- Added unit test `test_get_media_items_by_ids_success` in `test_db_functions.py` to verify the functionality of `get_media_items_by_ids`.
> feat: Add `get_media_items_by_ids` function and integrate it into item removal process

- .github/workflows/docker-build-dev.yml
- Build dev image from main, workflow should be PR -> main, not PR -> branch -> main.
Release-As: 0.10.5
> ci: build dev image from main

- src/program/settings/models.py
Resolves: #611
- Updated subtitles provider variables in **models.py** for correct user credential use.
settings.json values for subtitle providers opensubtitlescom opensubtitles needs to be corrected to name without vip, post_processing/subliminal line:22 looks for values of providers without the vip.
> fix: updated settings.json variables for opensubtitles

- src/controllers/items.py
- src/program/downloaders/realdebrid.py
Resolves: rivenmedia/riven-frontend#5
The backend part of rivenmedia/riven-frontend#108. I would like to ask the reviewers to check the code carefully as I'm not yet fully familiar with the backend workings of the project. Also partially solves #726 and #605
> feature: Replace torrents with magnet links

- src/program/symlink.py
Looks like there was some duplicate code here. I've kept the two methods but updated the public method to call the internal one.
> refactor: remove duplicate method `symlink(item)`

- src/tests/test_symlink_library.py
Small change to get pytest passing for the symlink library. Some mandatory settings have been added since these tests were written.
> test: fix failing symlink library tests

- src/program/symlink.py
- src/tests/test_symlink_creation.py
I found it a bit hard to change the code here without tests, so I added some. This also found a couple of bugs:
- `update_item_folder` was causing some weird behaviours with files in the rclone root, and also when `alternative_folder` was used. I can't see anywhere that's required, so I removed it.
- There were two different, conflicting ways of finding the media in the rclone path. I removed the more simplistic one.
I also added some type checks / empty value checks and marked private methods as such.
This _should_ merge cleanly with #758, which removes a bunch of duplicate code also related to symlinks.
> test: add tests for symlink creation

- src/program/content/plex_watchlist.py
The Plex watchlist content service never returned any items because in the `_get_items_from_watchlist()` function, all the items got added to the recurring items list and got filtered out in line 74. But they should only be added to the recurring items list on line 75.
> Plex watchlist not returning any items

- src/program/db/db_functions.py
The deletion functionality was broken recently. When deleting a movie, the function wouldn't delete the Movie relation and would throw an error because of constraints.
> fix: delete the movie relation before deleting the mediaitem

- src/utils/notifications.py
If notifications are enabled is already checked in the post processing `__init__.py` and the item type is checked in the `notify_on_complete`
> refactor: remove unnecessary checks for notifications

- src/controllers/items.py
- src/program/downloaders/__init__.py
- src/program/downloaders/alldebrid.py
- src/program/downloaders/realdebrid.py
- src/program/downloaders/shared.py
- src/program/downloaders/torbox.py
- src/tests/test_alldebrid_downloader.py
There are a few places where modules are calling directly into a downloader's internal helper methods, causing tight coupling to RealDebrid. Notably this was happening in `src/controllers/items.py`, which was hitting RealDebrid for torrent information even when RD wasn't the configured downloader service. This causes breakage for other downloaders.
I've introduced an abstract base class for downloaders to implement, which is mostly complete.`get_torrent` is notably still missing, but I think it's unused at the moment.
While I was changing the downloaders I ran Black across them to get some style consistency - [that commit](https://github.com/rivenmedia/riven/blob/6ad6d4ddbf01593453c12b39773c07cd028bd261/src/program/libraries/symlink.py#L105) can be kept or dropped if it's too noisy.
> refactor: use an abstract base class for downloaders

- src/program/db/db_functions.py
- src/program/media/item.py
- src/program/symlink.py
- src/routers/secure/items.py
- src/utils/event_manager.py
Resolves: #772
This also removes redundant state determination and the item is assigned a state, not sure if its the best approach.
> fix: future cancellation resulted in reset, retry endpoints fialing

- src/program/db/db_functions.py
- src/program/managers/event_manager.py
- src/program/media/item.py
- src/program/services/indexers/trakt.py
- src/program/types.py
- src/routers/secure/items.py
- Changed MediaItem ID type from int to str to support composite keys.
- Added a method to generate composite keys using item type and trakt_id.
- Updated related functions and methods to handle the new ID type.
- Modified database queries and relationships to accommodate string IDs.
- Adjusted API endpoints and event management to work with composite keys.
> refactor: implement composite key generation for MediaItem

- src/program/services/scrapers/mediafusion.py
> fix: mediafusion sometimes throwing error when parsing response

- src/program/utils/request.py
- src/tests/test_rate_limiting.py
- Introduced retry policy and connection pool configuration in `create_service_session`.
- Added `get_retry_policy` and `get_http_adapter` functions for customizable retry and connection settings.
- Updated tests to cover new session adapter configurations and ensure correct behavior.
> feat: add retry policy and connection pool configuration to request utils
